### ISSUE TITLE
Skeleton = Placeholder?

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#106]
I saw in other Reshaped components regularly the usage of the `Placeholder` component. With 1.10 the `Skeleton` component is now introduced. Is that not the same? 

If yes:
1. I think it would be great to have a consistent usage of this throughout the documentation. So I have an indirect learning of the Skeleton component, while learning about the other components. And I'm not getting confused with two different types.
2. If I search for `Placeholder` I would expect the `Skeleton` component and not the `Image` component
![image](https://user-images.githubusercontent.com/87228994/212490547-7359ea80-86c8-466d-a0cf-18eaa986d061.png)

**Comment by blvdmitry** [comment]
I think I should actually replace Placeholder with View in those examples. Placeholder is just an internal utility I used in Storybook originally and had secretly exported from the library because View was not yet implemented :)

**Comment by blvdmitry** [comment]
Updated all examples for the next release
