### ISSUE TITLE
Move Sandwich from top right to bottom right

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#107]
I find it quite hard to reach every time the sandwich menu in the left and right top corner of my Smartphone. And it seems that there are also some analyzis about it
![Screenshot_20230115-085911.png](https://user-images.githubusercontent.com/87228994/212529452-68782506-0237-43b1-9f20-53ab7060e964.png)

Maybe you want to think about moving it to the bottom right or left. HeadlessUi has that too and if feels quite comfortable

![Screenshot_20230115-085119.png](https://user-images.githubusercontent.com/87228994/212529471-5eb47269-6fb5-42ba-b565-76fe962d6542.png)

**Comment by blvdmitry** [comment]
Done for the next roll out
<img width="374" alt="image" src="https://user-images.githubusercontent.com/887379/222010607-422c2802-cb0c-4511-bef8-46b0f131374b.png">
