### ISSUE TITLE
Question: Figma library

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#123]
This section confuses me every time 🙈
https://reshaped.so/content/docs/getting-started/figma/libraries#use-libraries

So should I only activate Dark OR Light library, or can I also activate BOTH?

**Comment by mmailaender** [comment]
After playing some minutes with it and activating Dark/Light and then keeping it completely off, I'm now completely confused why I'm overall need to activate it?

![image](https://user-images.githubusercontent.com/87228994/215323725-8e8caa6a-c33e-46c0-addc-d8c9aa1fe153.png)

The reshaped plugin also works without having Dark OR/AND Light activated.

**Comment by blvdmitry** [comment]
The reason for that, is to make sure that when you're building custom components using our tokens – it also works correctly with theming. When you apply a theme in the plugin it finds all the styles with the token names found during them import and swaps the values to the picked theme. So in case you're applying a theme to the whole page but then some token values were used from another theme/mode – they will get reset to the theme you pick.

I'm updating the Figma docs today so going to take a look at this section as well

**Comment by mmailaender** [comment]
But what should happen, if I **deactivate** light library and **activate** dark library? Based on what you're saying, I would expect that it would update the assigned colors, or? (Similar to the theming plugin, but file wide) Because currently it seems for me, that it makes no difference to switch from Light to Dark library.

**Comment by blvdmitry** [comment]
Libraries you enable show in this popup when you pick which styles to apply to your custom frames. If you have both of them enabled – tokens from both library will appear in this menu:
<img width="242" alt="image" src="https://user-images.githubusercontent.com/887379/215336508-b0b1db5f-6276-4263-908b-b437dec3712a.png">

**Comment by mmailaender** [comment]
Ahhhh - that's the missing puzzle piece - At the moment I'm activating both, e.g. Foreground/Neutral is not existing once, it's existing twice (`Reshaped styles - Light v1.11` & `Reshaped styles - Dark v1.11`). And Figma is differentiating it. Intuitively I thought it's only existing once, and based on what I'm activating, it's overwriting the color code.

Thx for the explanation! :)
