### ISSUE TITLE
Improve Getting started

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#126]
Feedback for https://reshaped.so/content/docs/getting-started/react/installation

Currently, the `Getting Start` section mixes tasks and background information. I think it could help to differentiate it to make the getting started process more fluent.

1. Putting the Framework selection at the top
![image](https://user-images.githubusercontent.com/87228994/216845585-03001b3f-cd2c-4751-ae9b-89543bc4eb35.png)
I've seen it quite often from others and I think it's a great way to directly start with the fitting docs
![image](https://user-images.githubusercontent.com/87228994/216845666-6af6c31c-782a-40ed-9856-9cc590f43886.png)

2. Split `Setup CSS` in task and explanation section
e.g.
Create `postcss.config.js` in your project root 
```js
const postcss = require("reshaped/postcss");
module.exports = postcss.config
```

Info Box:
Reshaped relies on CSS Modules and PostCSS to isolate our styles and support custom media queries. Additionally, we're keeping CSS imports in our JS files to ensure CSS tree-shaking is working. This way, you will get CSS only for components you use in the product instead of importing CSS for the whole library.
Our config enables custom media queries provided by Reshaped, autoprefixer, and cssnano for build optimizations. This config can be extended with your own plugins.

3. Put `Public API` at the end, and `Start using Reshape` before
I like the way how [React Flow](https://reactflow.dev/docs/quickstart/) was pointing it "For folks who want to get React Flow up and running fast and figure out the details later, this is the site for you."

**Comment by blvdmitry** [comment]
Updated the structure of the page and removed unrelevant content, going to be live in the next release
