### ISSUE TITLE
[Figma] design token not applied to Text component

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#128]
Utilities > icon
![image](https://user-images.githubusercontent.com/87228994/217212201-d49cb774-c585-4d35-9904-f66483071dda.png)

And as you can see, the tokens are not applied as default:
![image](https://user-images.githubusercontent.com/87228994/217212494-bb8631ce-459b-4d11-87e6-c05c55054b35.png)

And you're using SF Pro for some typography (Title 1, Title 2, etc.) which only seems available as standard on some machines. e.g., on my colleague's mac, it's not available:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/87228994/217213111-3f9ce901-c14b-4da2-8db6-be662b8310bc.png)

**Comment by blvdmitry** [comment]
Thanks for sharing, going to take a look a bit later this week. I wonder if meanwhile a workaround that works would be dowloading the font from the Apple website: https://developer.apple.com/fonts/

**Comment by blvdmitry** [comment]
Updated the information about this in the Figma installation guide for the next release since it works differently from the browser font cascades. Going to revisit this again in v2 since we have some plans around the typography tokens structure.
