### ISSUE TITLE
[Bug] Tailwind setup failed

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#131]
I tried to set up Tailwind with Reshaped (Used this documentation: https://tailwindcss.com/docs/guides/nextjs)

It's not working atm, so is there some potential conflict with Reshaped? (It's not throwing any errors)

I also tried it with this posstcss.config.js because I saw that Reshaped is exporting its own PostCSS config:

```js
const postcss = require("reshaped/postcss");
module.exports = {
    plugins: {
        ...postcss.config.plugins,
        tailwindcss: {},
    }
}
```

**Comment by blvdmitry** [comment]
This issue should be resolved now with https://github.com/formaat-design/community/tree/master/examples/integration-tailwind

**Comment by mmailaender** [comment]
@blvdmitry 
The postcss config is not yet covered by your docs:

Tailwind: https://tailwindcss.com/docs/using-with-preprocessors#build-time-imports
Reshaped: https://reshaped.so/content/docs/getting-started/react/installation#setup-css

It would be good if you provided a code snippet that brings both together.

**Comment by blvdmitry** [comment]
Adding this little bit from the repository example: 
<img width="772" alt="image" src="https://user-images.githubusercontent.com/887379/235211629-097d4be5-ad7e-4580-9f6c-361f4cf9e377.png">

**Comment by mmailaender** [comment]
@blvdmitry What do you think about adding Tailwind natively to the reshaped installation? It's a dev dependency, so it has no negative impact on the bundle size. On the other side, it would increase the convenience and easiness to use.

**Comment by blvdmitry** [comment]
It might be an issue if there are breaking changes coming from a major Tailwind release at some point but the product using reshaped is not yet ready to migrate. We'll lock the people out from upgrading for no reason

**Comment by mmailaender** [comment]
You can do it like Nextjs with their newest CLI in update 13.4
![image](https://user-images.githubusercontent.com/87228994/236270922-e8c1e090-672b-40e1-8c66-682d1b3d57e8.png)

Btw. 13.4 is simply AMAZING

**Comment by blvdmitry** [comment]
Ah, so I think you mean it would benefit to have create-reshaped-app then with multiple options, since Next CLI installs Tailwind into your project and you then have full control over the version
