### ISSUE TITLE
Global CSS can't be imported from with in node_modules

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#144]
Using Nextra with Nextjs

 https://nextjs.org/docs/messages/css-npm

![image.png](https://user-images.githubusercontent.com/87228994/225988993-1c15b8db-095a-4dbd-8167-3e0689045c82.png)

**Comment by blvdmitry** [comment]
Are you using the app directory in this project or still the pages directory?

**Comment by zlpkhr** [comment]
I found out that it can be fixed, if you add reshaped into transpile list in next config. Then you can use reshaped as normal, without importing from `reshaped/bundle`. I guess it would be helpful to show in the docs.

```js
// next.config.js

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ['reshaped']
}

module.exports = nextConfig;
```

**Comment by mmailaender** [comment]
It does not make any difference for me while using Nextra.  Still getting the same error when using `import { View, Text, Avatar } from "reshaped";`.

```js
import nextra from "nextra";
import { remarkMermaid } from "remark-mermaid-nextra";

/**
 * @type {import("nextra").NextraConfig}
 */
const nextraConfig = {
  transpilePackages: ["reshaped"],
  latex: true,
  mdxOptions: {
    remarkPlugins: [remarkMermaid],
  },
  theme: "nextra-theme-docs",
  themeConfig: "./theme.config.tsx",
};

const withNextra = nextra(nextraConfig);

export default withNextra();
```
