### ISSUE TITLE
Adapting accordion concept to Tabs etc.

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#90]
First: I think your concept that you introduced with Accordion and View is simply brilliant - Have not seen it before, but after I understood the concept it's extremely easy to use and adds a drastically higher flexibility for me. So great job! ❤️

Brings me to the point, that I'm now fixed on, and I would like to use this concept also for Tabs etc. 😉 

```
<Tabs variant="pills-elevated">
  <Tabs.List>
    <View direction="column">
      <Tabs.Item value="0">List view</Tabs.Item>
      <Tabs.Item value="1">Map view</Tabs.Item>
    </View>
  </Tabs.List>
</Tabs>
```

**Comment by blvdmitry** [comment]
Hm, that's an interesting one. I've got to revisit my decision making there since I might have done it intentionally in case this doesn't work right now. But right now I see no reason about why not :)

**Comment by blvdmitry** [comment]
Yeah, for multiple selection (since you also probably don't need the sliding animation), I would just use a hidden checkbox. We actually have an internal utility that we use in Checkbox and Radio components, so we can make it public as well and it then can be combined either with the Card selected prop or with custom components using <label>

**Comment by blvdmitry** [comment]
Looking at the implementation I think there were 2 good reasons to have the List wrapper only accept Tabs.Item
- it lets us collect an array of refs to then operate with them as an array, even if they get rendered in wrong order and set the default selection automatically
- it provides additional functionality for cases when all items don't fit into the parent

So a question for you would be – do you need vertical tabs now for any use case or should we park it for now and keep in mind that could implement vertical direction for the component which would also work well with underlined tabs and still handle the animation and scrolling correctly?

**Comment by mmailaender** [comment]
Yes, we need vertical tabs e.g. 
![image](https://user-images.githubusercontent.com/87228994/208374916-984c5bba-a17f-4df1-a3ea-5323e3459bb2.png)

I'm not sure if you have checked out the "flexible tabs" from Plasmic, but it's quite easy to achieve your 2nd point. (And they're working with Vertical and horizontally stacks)

Regarding your first point: I think `View` is only affecting UI, so it should not affect your functional aspect, or?

**Comment by blvdmitry** [comment]
If we use View inside that means it can be not just View but any nesting inside the list that we should support and in both cases we no longer can map over children with React API.  So I'm currently leaning towards introducing a prop for vertical direction so we can handle all UI features of Tabs correctly.

Where should I look for the Plasmic tabs? (not that experience with it besides checking their progress)

**Comment by blvdmitry** [comment]
Also, looking at your menu – I think we can support rendering non Tabs.Item elements inside the list just fine, so it should help in your case I assume

**Comment by mmailaender** [comment]
Login into Plasmic and click on the plus button
![image](https://user-images.githubusercontent.com/87228994/208704205-81776573-16ac-43c1-9e6b-c55a302b2acd.png)

and then search for `flexible tabs`
![image](https://user-images.githubusercontent.com/87228994/208753619-277d8c2c-89c0-440e-ae17-a39dbbeb9f01.png)


The mapping could be maybe something like this 🤔 
![image](https://user-images.githubusercontent.com/87228994/208754587-a13bc8ef-d5a8-415d-ae50-e2280fd7dbca.png)

**Comment by blvdmitry** [comment]
Do I get it right that in their case if you try moving the items outside the stacks - the component breaks?
That's more of a side note though since I think if I try to change the Stack to vertical - Tabs stop working. Additionally all the dynamic behaviour doesn't have to be supported in their case, so I'm still leaning towards implementing direction through a prop + allow customisation of item and adding non-interactive elements

**Comment by mmailaender** [comment]
That's the cool thing - Stack is only helping you to structure and design it the way you want it - it stays fully function with or without the stack:

![image](https://user-images.githubusercontent.com/87228994/208868636-31cba377-b6e3-4dae-acce-bce416516006.png)

Clicking on Tab 1
![image](https://user-images.githubusercontent.com/87228994/208868697-ec7a3aee-e15e-434f-9edb-b5b4565ac288.png)

Clicking on Tab 2
![image](https://user-images.githubusercontent.com/87228994/208868751-5b0121e8-42b8-4082-9ac3-c404c8ec1d57.png)

As I initially said - I think the concept that you start pushing with Accordion & View is quite fantastic because high flexibility and simplicity at the same time - And Plasmic is pushing the same Idea also here to Tabs :)

**Comment by blvdmitry** [comment]
Adding column direction and non-interactive item support in the next release, just merged it 

<img width="781" alt="image" src="https://user-images.githubusercontent.com/887379/215297346-2c4e6079-1321-4686-ba1d-ad30d212e21c.png">
