### ISSUE TITLE
View documentation - Justify not experienceable

### ISSUE THREAD

**Issue by mmailaender** [formaat-design/community#96]
Justify="end"
![image](https://user-images.githubusercontent.com/87228994/209428078-4777fe9c-50ed-4939-a626-a5bca1238a7a.png)

Justify="start"
![image](https://user-images.githubusercontent.com/87228994/209428091-606b75b5-3afc-4502-a41f-ad61187c1d11.png)

As you can see, no difference, because "grow" is default active:
![image](https://user-images.githubusercontent.com/87228994/209428116-644b9089-d466-4a9c-8fb8-de8eac125963.png)

Maybe it's helpful to have it default deactivated to better showcase the different modes? :)

**Comment by blvdmitry** [comment]
This one turned out to be quite tricky without overcomplicating the demo controls API just for one specific use case. I'll think what's the best approach for it without showing a demo that makes less sense

**Comment by blvdmitry** [comment]
Updated for the next rollout
